// Package hugo Code generated by go-bindata. (@generated) DO NOT EDIT.
// sources:
// config.json
// params.dev.json
// params.json
package hugo

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

// Name return file name
func (fi bindataFileInfo) Name() string {
	return fi.name
}

// Size return file size
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}

// Mode return file mode
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}

// ModTime return file modify time
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}

// IsDir return file whether a directory
func (fi bindataFileInfo) IsDir() bool {
	return fi.mode&os.ModeDir != 0
}

// Sys return file is sys mode
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _configJson = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x6c\x90\xbd\x6e\xeb\x30\x0c\x85\x77\x3f\x85\xa0\x39\xf7\xfa\xde\x35\xcf\x90\x2e\x05\x3a\x15\x19\x68\x89\xb6\x05\xff\x50\x10\xa9\x04\x6d\x91\x77\x2f\x24\x59\x76\x0a\x74\xb2\xcf\xe1\x21\xf9\x89\x5f\x8d\x52\x1a\x98\x51\x58\x9f\x55\x52\x4a\xe9\x80\x9e\xde\x5e\x2f\xfa\xac\xf4\x28\xe2\xf9\xdc\xb6\x83\x93\x31\x76\x7f\x0d\x2d\x2d\x78\xcf\x86\x2c\xb6\x2c\x20\xce\xfc\xd9\xba\x4f\xa5\xf7\x86\x81\x1d\xad\xa9\x77\x01\x16\x0c\xb5\x60\x5d\x38\x56\x24\x0d\x02\x29\x95\xbf\xa7\xea\xba\x05\x06\x4c\x39\x5d\xa6\xb7\x65\x7a\xbb\xf9\x7b\xae\x77\xf3\x8f\x58\xd1\xb9\xfa\x68\x94\x7a\xa4\xa0\x36\x33\x45\x9b\x52\xef\x05\x01\xee\x3b\x26\x7c\xc6\x80\x55\x0c\x06\x0f\xca\xc1\x09\xcc\x64\x10\xd6\xea\xcd\x6e\x25\xbb\x27\xc8\xe3\xca\x02\x66\xaa\x86\x07\x33\xa1\x54\xd5\x41\xc0\x05\x05\xe6\x7d\x22\x99\x09\x43\x42\xbb\x66\x28\x1f\xc8\x46\x23\x2f\xb8\xc6\xe3\xe2\xe6\x5f\xa2\xd4\x53\xec\xd0\x76\xfa\x94\x9f\xc5\x63\xfa\x49\xd6\x0d\xe2\x2c\x55\xf4\x14\x16\x7d\xdd\xdf\x48\xcc\xbf\x8e\xba\xd1\x07\x0c\xe9\xfa\x4a\x0f\x11\x82\xad\xed\x56\x5f\x37\x30\xf3\x3f\x07\xfd\x08\x61\x29\x41\xbe\xbb\x3e\xef\x61\x84\x60\xc6\xd9\x0d\xa3\x3c\xad\xea\x89\x04\xc3\xc5\xad\xd3\xd3\x4d\x2b\x72\x51\x1b\xf6\x51\xda\xd0\x0f\x23\xe3\xa7\x63\x34\x8f\xe6\x3b\x00\x00\xff\xff\xcf\x16\xd2\x4a\x7d\x02\x00\x00")

func configJsonBytes() ([]byte, error) {
	return bindataRead(
		_configJson,
		"config.json",
	)
}

func configJson() (*asset, error) {
	bytes, err := configJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "config.json", size: 637, mode: os.FileMode(420), modTime: time.Unix(1601449236, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _paramsDevJson = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x84\xd2\xb1\x6e\xf2\x30\x14\x05\xe0\x9d\xa7\x40\x99\xfe\x5f\x6d\x42\xa1\x14\x21\xa6\x56\x5d\xda\xb1\x4f\x80\x6c\xe7\x92\x58\x38\xb9\x96\x7d\x9d\x08\x55\x7d\xf7\x0a\x9b\x20\x63\x52\x58\x8f\xcf\xa7\x93\xc8\xfe\x9e\x4c\xa7\x59\x89\x0d\x93\xed\x96\x69\x6d\x05\x96\x90\x6d\xa6\x59\x4d\xa4\xed\x66\x36\x1b\xb2\xbc\x7b\xce\x6b\x57\x61\xd1\x03\x2f\x98\xd6\xd9\x63\x04\x2d\x31\x5b\xc7\xca\x07\x50\xe6\xdd\xfc\x6f\xb4\x77\x1c\x4a\x1e\xab\x90\xe4\xdd\xe2\x36\xea\x98\x53\x94\x3a\x1f\xde\xdd\xdb\xa1\x69\x52\x79\xcc\x6e\x42\x5d\x33\xd3\x80\x89\xdd\x29\xba\xbb\x27\x64\xba\x26\xe4\x5d\x64\x6b\x09\xaa\x4c\x61\x48\x6f\x62\x7e\x20\xe0\x4e\xaa\x12\x8c\x8d\xf9\x31\x2f\xce\x07\xb1\x68\x98\xd9\x03\x69\xc5\xc4\xc5\xa5\x47\x71\x31\x82\xb9\xc2\x6a\xeb\x8c\xba\xd8\x50\x58\x8d\x75\xad\x62\x62\x9f\x96\x7d\x58\x0c\x4f\xab\x10\xd8\x84\x72\x25\xa9\x76\x3c\x6d\x87\xf4\xd8\x3a\xbf\xc6\x50\xa7\x5e\x12\x81\x49\xfb\xa7\xd8\x83\x37\xad\xed\x3b\x96\xf0\xf1\x15\xc8\x8e\x09\xe0\x88\x57\x5f\xd4\xf7\x7d\x31\x9c\x8d\x2c\x1d\xd0\x91\xe3\x30\xa6\x4e\x47\x1e\x89\xf3\xde\x67\x2b\x82\x14\xd8\x12\x13\xb4\x85\x86\x49\x6f\xad\xd3\x1a\x0d\xbd\x5e\xff\xfd\x50\xd5\x35\xb6\xfe\x3a\x1e\xe6\xff\x56\x2f\x4f\xff\x17\xcb\x79\xbe\x5e\xae\x57\xd9\xe4\xe7\x37\x00\x00\xff\xff\x87\xfa\xd8\x2f\xae\x03\x00\x00")

func paramsDevJsonBytes() ([]byte, error) {
	return bindataRead(
		_paramsDevJson,
		"params.dev.json",
	)
}

func paramsDevJson() (*asset, error) {
	bytes, err := paramsDevJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "params.dev.json", size: 942, mode: os.FileMode(420), modTime: time.Unix(1593072898, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _paramsJson = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x6c\x92\xc1\x4e\x03\x21\x10\x86\xef\x7d\x8a\x66\x4f\x1a\x95\x5a\x53\x9b\xa6\x27\x8d\x17\x3d\xfa\x04\x0d\xb0\xd3\x2e\x29\xec\x10\x18\xdc\x34\xc6\x77\x37\x0b\x6d\x43\x61\xaf\xdf\x7c\xff\xcc\x90\xe1\x77\x36\x9f\x37\x2d\x1a\xae\xfa\x1d\xb7\xd6\x4b\x6c\xa1\xd9\xce\x9b\x8e\xc8\xfa\xed\x62\x71\x61\x4c\xa2\x69\x1e\x33\xd9\x13\xf7\x5d\x6e\x46\xc0\x5c\xe8\x6f\xb4\x63\x10\xd0\x8a\xdc\x4b\xa4\xea\x37\xe2\x1f\x1e\x34\x95\x6e\x84\x93\xfa\x1e\x9d\x29\xed\x91\x55\xb2\xed\xb8\x33\xe0\x72\xf7\x8c\x98\xc2\xaa\xad\x54\x65\x53\x26\x55\x65\xf9\x4e\x81\x6e\x4b\x33\xd1\x6a\x01\x71\x22\x10\x41\xe9\x16\x9c\xcf\x23\x23\x67\xd7\x42\x9e\x30\xdc\x1d\x81\xac\xe6\xf2\xe6\x1c\x19\x66\x13\x61\xa1\xf1\xb0\x0b\x4e\xdf\xcc\xd0\x78\x98\x72\xbd\xe6\xf2\x58\xca\x11\xb2\xfa\xe8\x07\x45\x5d\x10\xa5\x9d\xe8\x68\x5d\xff\x49\xd2\x69\x50\x44\xe0\x4a\xff\x8c\x63\xe0\xdd\x5a\xff\x81\x2d\x7c\x7e\xa7\xc8\x9e\x4b\x10\x88\xd5\x46\xc3\x30\xb0\x4b\x6d\x62\xd2\x09\x03\x05\x01\x53\xa9\x73\x29\x86\xe4\x75\xde\x57\x2f\x53\x52\x62\x4f\x5c\xd2\x0e\x0c\x57\x31\xeb\x83\xb5\xe8\xe8\xad\x7e\xfd\x45\xb5\x1d\xf6\xf1\x1c\x0f\xcb\xbb\xf5\xeb\xf3\xfd\xcb\x6a\xf9\xb4\x59\x6d\xd6\xcd\xec\xef\x3f\x00\x00\xff\xff\xf7\xae\xc7\xf3\x48\x03\x00\x00")

func paramsJsonBytes() ([]byte, error) {
	return bindataRead(
		_paramsJson,
		"params.json",
	)
}

func paramsJson() (*asset, error) {
	bytes, err := paramsJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "params.json", size: 840, mode: os.FileMode(420), modTime: time.Unix(1593072898, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"config.json":     configJson,
	"params.dev.json": paramsDevJson,
	"params.json":     paramsJson,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"config.json":     &bintree{configJson, map[string]*bintree{}},
	"params.dev.json": &bintree{paramsDevJson, map[string]*bintree{}},
	"params.json":     &bintree{paramsJson, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
